2013/03/16 01:05:51 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/cde/www/V/assets" 是无效的. 请确定它是一个可被 Web server process 写入资料的目录.' in /cde/www/V/protected/libs/yii/web/CAssetManager.php:138
Stack trace:
#0 /cde/www/V/protected/libs/yii/web/CAssetManager.php(123): CAssetManager->setBasePath('/cde/www/V/asse...')
#1 /cde/www/V/protected/libs/yii/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /cde/www/V/protected/extensions/popup/popup.php(21): CAssetManager->publish('/cde/www/V/prot...')
#3 /cde/www/V/protected/libs/yii/web/CBaseController.php(173): popup->run()
#4 /cde/www/V/protected/modules/Home/views/main/main.php(17): CBaseController->widget('ext.popup.popup')
#5 /cde/www/V/protected/libs/yii/web/CBaseController.php(126): require('/cde/www/V/prot...')
#6 /cde/www/V/protected/libs/yii/web/CBaseController.php(95): CBaseController->renderInternal('/cde/www/V/prot...', NULL, true)
#7 /cde/www/V/protected/libs/yii/web/CController.php(869): CBaseController->renderFile('/cde/www/V/prot...', NULL, true)
#8 /cde/www/V/protected/libs/yii/web/CController.php(782): CController->renderPartial('main', NULL, true)
#9 /cde/www/V/protected/modules/Home/controllers/MainController.php(7): CController->render('main')
#10 /cde/www/V/protected/libs/yii/web/actions/CInlineAction.php(49): MainController->actionIndex()
#11 /cde/www/V/protected/libs/yii/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /cde/www/V/protected/libs/yii/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /cde/www/V/protected/libs/yii/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /cde/www/V/protected/libs/yii/web/CWebApplication.php(282): CController->run('index')
#15 /cde/www/V/protected/libs/yii/web/CWebApplication.php(141): CWebApplication->runController('Home/main/index')
#16 /cde/www/V/protected/libs/yii/base/CApplication.php(169): CWebApplication->processRequest()
#17 /cde/www/V/index.php(35): CApplication->run()
#18 {main}
REQUEST_URI=/V/
---
2013/03/16 01:12:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'yii_test'' in /cde/www/V/protected/libs/yii/db/CDbConnection.php:381
Stack trace:
#0 /cde/www/V/protected/libs/yii/db/CDbConnection.php(330): CDbConnection->open()
#1 /cde/www/V/protected/libs/yii/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /cde/www/V/protected/libs/yii/base/CModule.php(387): CDbConnection->init()
#3 /cde/www/V/protected/libs/yii/base/CApplication.php(438): CModule->getComponent('db')
#4 /cde/www/V/protected/libs/yii/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /cde/www/V/protected/libs/yii/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /cde/www/V/protected/libs/yii/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /cde/www/V/protected/modules/UserCenter/models/User.php(20): CActiveRecord::model('User')
#8 /cde/www/V/protected/components/UserIdentity.php(22): User::model()
#9 /cde/www/V/protected/modules/UserCenter/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /cde/www/V/protected/libs/yii/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /cde/www/V/protected/libs/yii/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /cde/www/V/protected/libs/yii/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /cde/www/V/protected/modules/UserCenter/controllers/LoginController.php(19): CModel->validate()
#14 /cde/www/V/protected/libs/yii/web/actions/CInlineAction.php(49): LoginController->actionLogin()
#15 /cde/www/V/protected/libs/yii/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /cde/www/V/protected/libs/yii/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /cde/www/V/protected/libs/yii/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /cde/www/V/protected/libs/yii/web/CWebApplication.php(282): CController->run('login')
#19 /cde/www/V/protected/libs/yii/web/CWebApplication.php(141): CWebApplication->runController('UserCenter/logi...')
#20 /cde/www/V/protected/libs/yii/base/CApplication.php(169): CWebApplication->processRequest()
#21 /cde/www/V/index.php(35): CApplication->run()
#22 {main}
REQUEST_URI=/V/login
HTTP_REFERER=http://localhost/V/login
---
2013/03/16 01:37:47 [error] [php] session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Cannot regenerate session id - headers already sent (/cde/www/V/protected/libs/yii/web/CHttpSession.php:185)
Stack trace:
#0 /cde/www/V/protected/libs/yii/web/auth/CWebUser.php(227): CWebUser->changeIdentity()
#1 /cde/www/V/protected/modules/UserCenter/models/LoginForm.php(71): CWebUser->login()
#2 /cde/www/V/protected/modules/UserCenter/controllers/LoginController.php(19): LoginForm->login()
#3 /cde/www/V/protected/libs/yii/web/actions/CInlineAction.php(49): LoginController->actionLogin()
#4 /cde/www/V/protected/libs/yii/web/CController.php(308): CInlineAction->runWithParams()
#5 /cde/www/V/protected/libs/yii/web/CController.php(286): LoginController->runAction()
#6 /cde/www/V/protected/libs/yii/web/CController.php(265): LoginController->runActionWithFilters()
#7 /cde/www/V/protected/libs/yii/web/CWebApplication.php(282): LoginController->run()
#8 /cde/www/V/protected/libs/yii/web/CWebApplication.php(141): CWebApplication->runController()
#9 /cde/www/V/protected/libs/yii/base/CApplication.php(169): CWebApplication->processRequest()
#10 /cde/www/V/index.php(35): CWebApplication->run()
REQUEST_URI=/V/login
in /cde/www/V/protected/modules/UserCenter/models/LoginForm.php (71)
in /cde/www/V/protected/modules/UserCenter/controllers/LoginController.php (19)
in /cde/www/V/index.php (35)
2013/03/16 01:37:51 [error] [php] session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Cannot regenerate session id - headers already sent (/cde/www/V/protected/libs/yii/web/CHttpSession.php:185)
Stack trace:
#0 /cde/www/V/protected/libs/yii/web/auth/CWebUser.php(227): CWebUser->changeIdentity()
#1 /cde/www/V/protected/modules/UserCenter/models/LoginForm.php(71): CWebUser->login()
#2 /cde/www/V/protected/modules/UserCenter/controllers/LoginController.php(19): LoginForm->login()
#3 /cde/www/V/protected/libs/yii/web/actions/CInlineAction.php(49): LoginController->actionLogin()
#4 /cde/www/V/protected/libs/yii/web/CController.php(308): CInlineAction->runWithParams()
#5 /cde/www/V/protected/libs/yii/web/CController.php(286): LoginController->runAction()
#6 /cde/www/V/protected/libs/yii/web/CController.php(265): LoginController->runActionWithFilters()
#7 /cde/www/V/protected/libs/yii/web/CWebApplication.php(282): LoginController->run()
#8 /cde/www/V/protected/libs/yii/web/CWebApplication.php(141): CWebApplication->runController()
#9 /cde/www/V/protected/libs/yii/base/CApplication.php(169): CWebApplication->processRequest()
#10 /cde/www/V/index.php(35): CWebApplication->run()
REQUEST_URI=/V/login
in /cde/www/V/protected/modules/UserCenter/models/LoginForm.php (71)
in /cde/www/V/protected/modules/UserCenter/controllers/LoginController.php (19)
in /cde/www/V/index.php (35)
2013/03/17 12:27:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message '无法解析请求 "UserCenter/group/create"。' in /cde/www/V/protected/libs/yii/web/CWebApplication.php:286
Stack trace:
#0 /cde/www/V/protected/libs/yii/web/CWebApplication.php(141): CWebApplication->runController('UserCenter/grou...')
#1 /cde/www/V/protected/libs/yii/base/CApplication.php(169): CWebApplication->processRequest()
#2 /cde/www/v/index.php(35): CApplication->run()
#3 {main}
REQUEST_URI=/v/UserCenter/group/create
---
